# This workflow will do a clean install of node dependencies, build the source code for every push and pull requests

name: Lint & Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  LintBuild:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js 20
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20
      - name: 📦 Install Dependencies
        run: npm install
      - name: 🎨 Eslint
        run: npm run lint
      - name: 📦 Build
        run: npm run build
