# This workflow will do a clean install of node dependencies, build the source code for every push and pull requests

name: Lint & Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  createCRAAndLintBuild:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node.js 20
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
      - name: Create CRA from template
        run: npx create-react-app my-app --template file:../cra-template-quentinvdr .
      - name: 📦 Install Dependencies
        run: npm install
        working-directory: ./my-app
      - name: 🎨 Eslint
        run: npm run lint
        working-directory: ./my-app
